version: '3'

services:
  ibuqa:
    container_name: ibuqa
    build:
      context: ./
      dockerfile: Dockerfile
    image: ibuqa:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14.2-apline
    volumes:
      - postgres_data:var/lib/postgresql/postgres_data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ibuqa_api

volumes:
  postgres_data