version: '3.9'

services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ibuqa_api
    ports:
      - "5432:5432"

  ibuqa:
    container_name: ibuqa
    build:
      context: ./
      dockerfile: Dockerfile
    image: ibuqa:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db

volumes:
  postgres_data: