# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

orbs:
  heroku: circleci/heroku@0.0.10
workflows:  
  heroku_deploy:
    when: 
      equal: [ "push", << pipeline.parameters.GHA_Event >>]
    jobs:
      - heroku/deploy-via-git
