name: Django CI/CD Workflow

on:
  pull_request:
    branches: [master, main]
  push:
    branches: [master, main]

jobs:
  health-check-job:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix: 
        python-version: [3.7, 3.8, 3.9]

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        postgres:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Cache Dependency
          uses: actions/cache@v2
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
              ${{ runner.os }}-}-pip-
        - name: Setup Python ${{ matrix.python-version }} Environment
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: psycopg2 prerequisites
          run: sudo apt-get install libpq-dev
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt 
        - name: Run Migrations
          run: |
            python manage.py makemigrations
            python manage.py migrate
        - name: Run test
          

  package-job:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    needs: [health-check-job]
    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      

